version: '3'
services:
  nginx:
    image: lb:latest
    container_name: nginx
    ports:
        - 80:80
  app:
    image: app:latest
    container_name: app
    ports:
      - 8180
  app1:
    image: app1:latest
    container_name: app1
    ports:
      - 8180
  app2:
    image: app2:latest
    container_name: app2
    ports:
      - 8180
